### ISSUE TITLE
Pre-commit hook is created without execute permissions

### ISSUE THREAD

**Issue by juulhobert** [DanySK/gradle-pre-commit-git-hooks#10]
Hello,

The pre-commit hook file is created, but is missing the execute file permission. See:

-rw-r--r-- 1 <user> <group>   67 14 jan 10:27 pre-commit

**Comment by DanySK** [comment]
Hi @juulhobert, thank you for the report. I reproduced the issue.

**Comment by DanySK** [comment]
A solution has been concocted and should generate a new release shortly.
