### ISSUE TITLE
Error messages colors won't render on Git UIs

### ISSUE THREAD

**Issue by almogtavor** [DanySK/gradle-pre-commit-git-hooks#126]
### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

When I work with the Git CLI the error messages seem great. Looks like this:
![image](https://user-images.githubusercontent.com/70065337/178106743-8821da25-47f5-4592-96c0-f94a43560ef6.png)

But when I use Github Desktop the error message colors won't render and it looks pretty bad:
![image](https://user-images.githubusercontent.com/70065337/178106793-4d2565ef-71cf-43cb-992d-447f1f78fee8.png)

I'd like there to be an option for configuring what kind of error message to use - the one with the colors or the one without the colors. This way each user would be able to choose, based on how he & his team uses Git.

### Your configuration

Irrelevant

### Gradle build scan and relevant logs

Irrelevant

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by DanySK** [comment]
Please take a look at the solution proposed in #128
