### ISSUE TITLE
How to check the main branch only?

### ISSUE THREAD

**Issue by yydon** [DanySK/gradle-pre-commit-git-hooks#232]
I use the feature branch workflow and want to avoid following the conventional commits on the feature branch. How to check the main branch only? Thank you.

**Comment by DanySK** [comment]
Hi @yydon,
You must write your own git hook to do so, running `git brach` and verifying whether it is the branch you want to be checked. This plugin is meant to support the injection of scripts into git from a Gradle build, not as a replacement for writing hooks entirely.

**Comment by DanySK** [comment]
Closing
