### ISSUE TITLE
Adding configuration breaks existing dependencyResolutionManagement configuration

### ISSUE THREAD

**Issue by marvk** [DanySK/gradle-pre-commit-git-hooks#37]
Adding the required blocks to `settings.gradle` breaks my existing `dependencyResolutionManagement` configuration. I'm using the following configuration:

```kotlin
dependencyResolutionManagement {
    versionCatalogs {
        create("libs") {
            val basePluginVersion: String by settings
            from("my.group:my.version.catalog:$myVersionCatalogVersion")
        }
    }
}
```

and I get the following error when adding the git hooks configuration to settings.gradle and reloading:

```
A problem occurred configuring root project 'common-data'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find my.group:my.version.catalog:33.3.0.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/my/group/my.version.catalog/33.3.0/my.version.catalog-33.3.0.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

The version catalog is fetched from a private azure repository, and somehow, adding the required configuration seems to break the version catalog dependency resolution.

To be honest, I don't know if that's an oversight on my part, but maybe you have an Idea on how to resolve this anyways? Cheers.

**Comment by DanySK** [comment]
Hi, can you produce a minimal reproduction environment? The plugin does not really do much, I *guess* that the problem with your build is using the `plugins` block.

I think you may get the same effect by using the `buildscript` block: can you provide the entire `settings.gradle.kts`?

**Comment by DanySK** [comment]
I'm closing this as I need further information to debug the issue. Feel free to reopen or comment further if you can provide more data.
