### ISSUE TITLE
Plugin fails when checked out in a detached worktree

### ISSUE THREAD

**Issue by grodin** [DanySK/gradle-pre-commit-git-hooks#396]
### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Adding a detached worktree by `git worktree add -d some/directory` causes the plugin to fail with an `IllegalArgumentException` with message `No git root could be found in some/directory or any of its parent directories` (I've elided the actual directory names above).

The root cause of this is the function `File.isGitRoot()` which wants `.git` to be a directory.

See [this repo][1] for a reproduction of the bug.

[1]: https://github.com/grodin/org.danilopianini.gradle-pre-commit-git-hooks_repro

### Your configuration

```
plugins {
	id("org.danilopianini.gradle-pre-commit-git-hooks") version "1.1.9"
}

gitHooks {
    commitMsg { conventionalCommits() }
    createHooks()
}
```

### Gradle build scan and relevant logs

I haven't included a build scan as it's a bit overkill for this bug.

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by Ranbato** [comment]
On a related note, it also fails when hitting a repo cloned using SourceTree because their embedded git tool doesn't create a `.git/hooks` directory.  Creating the directory resolves the issue.

**Comment by DanySK** [comment]
@Ranbato fix for the issue you reported is upcoming.

**Comment by DanySK** [comment]
@grodin which would be the less surprising behavior in this case? I guess it'd be not creating any hook with no failure, but not touching the hooks on the original repo.

**Comment by grodin** [comment]
> @grodin which would be the less surprising behavior in this case? I guess it'd be not creating any hook with no failure, but not touching the hooks on the original repo.

I think that's probably the best option. I'm not actually sure what how git hooks behave in general when a worktree is checked out!

It might be worth emitting a warning even with the above strategy, just to make the user aware of what's happening.

**Comment by DanySK** [comment]
Can you try with version 2+ of this plugin? You should receive a warning stating that the plugin is not applying any configuration because you are in a detached worktree.
