### ISSUE TITLE
Allow commit messages not following the conventional commits format

### ISSUE THREAD

**Issue by cesarlp-pomelo** [DanySK/gradle-pre-commit-git-hooks#398]
In my team we use merge commits when pulling from develop to our feature branch (we don't rebase). The problem is that the "Merge ..." commit message does not follow the conventional commits format, and I do not know how to include it (because the commit message changes based on the current branch being worked on).

Is there any way to allow both conventional commits (for when we are working on our feature branch) + allowing merge/backport commits to be including when we pull current changes being made in the develop branch? For example:

Automatic PR from main to develop
Merge branch 'develop' into ...

Thanks

**Comment by DanySK** [comment]
Hi,
there are two solutions that come to my mind.

The most obvious is to [appropriately document your merges](https://www.phoronix.com/news/Linus-Torvalds-Git-Merge-Wisdom), as the creator of git warmly recommends. You just need to modify the merge pre-defined message with one compatible with conventional commits.

The second, which I do not recommend, is to add a custom hook that allows for merge commits, something like:

```kotlin
gitHooks {
    commitMsg {
        from{
            """your custom script running exit 0 in case of merge commit"""
        }
        conventionalCommits() // I'm not sure if this replaces the hook or adds, but it is worth trying
    } 
    createHooks()
}
```

**Comment by cesarlp-pomelo** [comment]
That makes sense, for some reason I didn't think about overriding the merge commit message. I'm closing the issue, thanks!
